using System;
using System.Collections.Generic;

namespace ImportDimensionCheck.Models
{
    public partial class BatchCode
    {
        public string Product { get; set; }
        public string BatchCode1 { get; set; }
        public string ProductName { get; set; }
        public double? Qty { get; set; }
        public string UOM { get; set; }
        public double? NetWgt { get; set; }
        public double? PackWgt { get; set; }
        public double? GrsWgt { get; set; }
        public string CONO { get; set; }
        public string MainWONO { get; set; }
        public string BOMNo { get; set; }
        public string Remark { get; set; }
        public string Printed { get; set; }
        public string PrintBy { get; set; }
        public DateTime? PrintDate { get; set; }
        public double? WIPQty { get; set; }
        public int? CurOprSeq { get; set; }
        public string CurOprCode { get; set; }
        public string CurOprDesc { get; set; }
        public string CurOprSts { get; set; }
        public string CurWO { get; set; }
        public string CurMC { get; set; }
        public string CurEmp { get; set; }
        public DateTime? CurStart { get; set; }
        public DateTime? CurFinish { get; set; }
        public bool? CurIsFirst { get; set; }
        public bool? CurIsLast { get; set; }
        public string CurEquipment { get; set; }
        public string CurStation { get; set; }
        public string Plant { get; set; }
        public int? NextOprSeq { get; set; }
        public string NextOprCode { get; set; }
        public string NextOprDesc { get; set; }
        public string DefectSts { get; set; }
        public double? DefectQty { get; set; }
        public string DefectReason { get; set; }
        public string DefectNote { get; set; }
        public string DefectBy { get; set; }
        public DateTime? DefectDate { get; set; }
        public string CauseReason { get; set; }
        public string CauseNote { get; set; }
        public string RecoverNote { get; set; }
        public string RecoverBy { get; set; }
        public DateTime? RecoverDate { get; set; }
        public string Rework { get; set; }
        public string ReworkBy { get; set; }
        public double? ReworkQty { get; set; }
        public DateTime? ReworkDate { get; set; }
        public string ReworkNote { get; set; }
        public int? ReworkOprSeq { get; set; }
        public string ReworkOprCode { get; set; }
        public string ReworkOprDesc { get; set; }
        public string ReworkMC { get; set; }
        public string ReworkStation { get; set; }
        public string Blocked { get; set; }
        public string BlockBy { get; set; }
        public DateTime? BlockDate { get; set; }
        public string BlockReason { get; set; }
        public string RestoreBy { get; set; }
        public DateTime? RestoreDate { get; set; }
        public string RestoreNote { get; set; }
        public string Damaged { get; set; }
        public string DamageNote { get; set; }
        public string DamageBy { get; set; }
        public DateTime? DamageDate { get; set; }
        public string Allocated { get; set; }
        public string AllocatedNote { get; set; }
        public string Verified { get; set; }
        public string VerifiedNote { get; set; }
        public string BatchCodeSts { get; set; }
        public string Zone { get; set; }
        public string Area { get; set; }
        public string BoxNo { get; set; }
        public string SmallBoxNo { get; set; }
        public string InStock { get; set; }
        public double? InStockQty { get; set; }
        public string WH { get; set; }
        public string BinLocation { get; set; }
        public string Received { get; set; }
        public string ReceiptBy { get; set; }
        public DateTime? ReceiptDate { get; set; }
        public DateTime? ExpireDate { get; set; }
        public string Checked { get; set; }
        public string CheckBy { get; set; }
        public DateTime? CheckDate { get; set; }
        public string CheckPeriod { get; set; }
        public string WgtSts { get; set; }
        public double? WgtBfr { get; set; }
        public double? WgtAft { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string ChangeBy { get; set; }
        public DateTime? ChangeDate { get; set; }
        public string ChangePatch { get; set; }
        public string WorkStation { get; set; }
        public string SaveBy { get; set; }
        public DateTime? SaveDate { get; set; }
        public double? ActQty { get; set; }
        public double? RmnQty { get; set; }
        public double? OrgQty { get; set; }
        public double? DfcQty { get; set; }
        public double? OpenQty { get; set; }
        public string ProductDesc { get; set; }
        public string CurWC { get; set; }
    }
}
